var annotated_dup =
[
    [ "tc", "namespacetc.html", [
      [ "io", "namespacetc_1_1io.html", [
        [ "DirectoryNotEmptyException", "classtc_1_1io_1_1_directory_not_empty_exception.html", "classtc_1_1io_1_1_directory_not_empty_exception" ],
        [ "DirectoryNotFoundException", "classtc_1_1io_1_1_directory_not_found_exception.html", "classtc_1_1io_1_1_directory_not_found_exception" ],
        [ "FileExistsException", "classtc_1_1io_1_1_file_exists_exception.html", "classtc_1_1io_1_1_file_exists_exception" ],
        [ "FileNotFoundException", "classtc_1_1io_1_1_file_not_found_exception.html", "classtc_1_1io_1_1_file_not_found_exception" ],
        [ "FileStream", "classtc_1_1io_1_1_file_stream.html", "classtc_1_1io_1_1_file_stream" ],
        [ "IOException", "classtc_1_1io_1_1_i_o_exception.html", "classtc_1_1io_1_1_i_o_exception" ],
        [ "IOUtil", "classtc_1_1io_1_1_i_o_util.html", null ],
        [ "IReadableSink", "classtc_1_1io_1_1_i_readable_sink.html", "classtc_1_1io_1_1_i_readable_sink" ],
        [ "ISink", "classtc_1_1io_1_1_i_sink.html", "classtc_1_1io_1_1_i_sink" ],
        [ "ISource", "classtc_1_1io_1_1_i_source.html", "classtc_1_1io_1_1_i_source" ],
        [ "IStorage", "classtc_1_1io_1_1_i_storage.html", "classtc_1_1io_1_1_i_storage" ],
        [ "IStream", "classtc_1_1io_1_1_i_stream.html", "classtc_1_1io_1_1_i_stream" ],
        [ "LocalStorage", "classtc_1_1io_1_1_local_storage.html", "classtc_1_1io_1_1_local_storage" ],
        [ "MemorySource", "classtc_1_1io_1_1_memory_source.html", "classtc_1_1io_1_1_memory_source" ],
        [ "MemoryStream", "classtc_1_1io_1_1_memory_stream.html", "classtc_1_1io_1_1_memory_stream" ],
        [ "OverlayedSource", "classtc_1_1io_1_1_overlayed_source.html", "classtc_1_1io_1_1_overlayed_source" ],
        [ "PaddingSource", "classtc_1_1io_1_1_padding_source.html", "classtc_1_1io_1_1_padding_source" ],
        [ "Path", "classtc_1_1io_1_1_path.html", "classtc_1_1io_1_1_path" ],
        [ "PathTooLongException", "classtc_1_1io_1_1_path_too_long_exception.html", "classtc_1_1io_1_1_path_too_long_exception" ],
        [ "PathUtil", "classtc_1_1io_1_1_path_util.html", null ],
        [ "sDirectoryListing", "structtc_1_1io_1_1s_directory_listing.html", "structtc_1_1io_1_1s_directory_listing" ],
        [ "StreamSink", "classtc_1_1io_1_1_stream_sink.html", "classtc_1_1io_1_1_stream_sink" ],
        [ "StreamSource", "classtc_1_1io_1_1_stream_source.html", "classtc_1_1io_1_1_stream_source" ],
        [ "StreamUtil", "classtc_1_1io_1_1_stream_util.html", null ],
        [ "SubSink", "classtc_1_1io_1_1_sub_sink.html", "classtc_1_1io_1_1_sub_sink" ],
        [ "SubSource", "classtc_1_1io_1_1_sub_source.html", "classtc_1_1io_1_1_sub_source" ],
        [ "SubStorage", "classtc_1_1io_1_1_sub_storage.html", "classtc_1_1io_1_1_sub_storage" ],
        [ "SubStream", "classtc_1_1io_1_1_sub_stream.html", "classtc_1_1io_1_1_sub_stream" ]
      ] ],
      [ "string", "namespacetc_1_1string.html", [
        [ "TranscodeUtil", "classtc_1_1string_1_1_transcode_util.html", null ]
      ] ],
      [ "AccessViolationException", "classtc_1_1_access_violation_exception.html", "classtc_1_1_access_violation_exception" ],
      [ "ArgumentException", "classtc_1_1_argument_exception.html", "classtc_1_1_argument_exception" ],
      [ "ArgumentNullException", "classtc_1_1_argument_null_exception.html", "classtc_1_1_argument_null_exception" ],
      [ "ArgumentOutOfRangeException", "classtc_1_1_argument_out_of_range_exception.html", "classtc_1_1_argument_out_of_range_exception" ],
      [ "ArithmeticException", "classtc_1_1_arithmetic_exception.html", "classtc_1_1_arithmetic_exception" ],
      [ "ByteData", "classtc_1_1_byte_data.html", "classtc_1_1_byte_data" ],
      [ "Exception", "classtc_1_1_exception.html", "classtc_1_1_exception" ],
      [ "InvalidOperationException", "classtc_1_1_invalid_operation_exception.html", "classtc_1_1_invalid_operation_exception" ],
      [ "NotImplementedException", "classtc_1_1_not_implemented_exception.html", "classtc_1_1_not_implemented_exception" ],
      [ "NotSupportedException", "classtc_1_1_not_supported_exception.html", "classtc_1_1_not_supported_exception" ],
      [ "ObjectDisposedException", "classtc_1_1_object_disposed_exception.html", "classtc_1_1_object_disposed_exception" ],
      [ "Optional", "classtc_1_1_optional.html", "classtc_1_1_optional" ],
      [ "OutOfMemoryException", "classtc_1_1_out_of_memory_exception.html", "classtc_1_1_out_of_memory_exception" ],
      [ "OverflowException", "classtc_1_1_overflow_exception.html", "classtc_1_1_overflow_exception" ],
      [ "PlatformErrorHandlingUtil", "classtc_1_1_platform_error_handling_util.html", null ],
      [ "UnauthorisedAccessException", "classtc_1_1_unauthorised_access_exception.html", "classtc_1_1_unauthorised_access_exception" ]
    ] ],
    [ "be_uint16_t", "structbe__uint16__t.html", "structbe__uint16__t" ],
    [ "be_uint32_t", "structbe__uint32__t.html", "structbe__uint32__t" ],
    [ "be_uint64_t", "structbe__uint64__t.html", "structbe__uint64__t" ],
    [ "le_uint16_t", "structle__uint16__t.html", "structle__uint16__t" ],
    [ "le_uint32_t", "structle__uint32__t.html", "structle__uint32__t" ],
    [ "le_uint64_t", "structle__uint64__t.html", "structle__uint64__t" ]
];